### ISSUE TITLE
request.query.type undefined

### ISSUE THREAD

**Issue by vinothwindows47** [muratcorlu/connect-api-mocker#13]
@muratcorlu 
![request_query_undefined](https://user-images.githubusercontent.com/3929019/34515916-80bcb6a6-f09a-11e7-93b7-1eba751d0f93.png)

**Comment by muratcorlu** [comment]
I think, everything is ok. :)

**Comment by vinothwindows47** [comment]
Thank you @muratcorlu it is my side understanding issue. 
 is it possible to give multiple proxy using express server ?

**Comment by muratcorlu** [comment]
Yes, your example should work. But keep in your mind, in this configuration, for example, if you make a request to `/backend/api/v1/users/1` and if you don't have a mock defined for that path than request will be proxied to `https://api.backend.yourdomain.com/backend/api/v1/users/1`. If you don't want to have `backend` prefix in your proxied url, then you need to rewrite in proxy configuration like:

```
proxy: {
    '/backend': {
        target: 'https://api.backend.yourdomain.com',
        pathRewrite: {"^/backend" : ""}
    }
....
```

Detailed information: https://webpack.js.org/configuration/dev-server/#devserver-proxy
