### ISSUE TITLE
Undefined baseUrl property when using with Connect

### ISSUE THREAD

**Issue by silentvick** [muratcorlu/connect-api-mocker#17]
Hi, I'm trying to setup mockers for my app using connect, but I get this error:

```
TypeError: Cannot read property 'replace' of undefined
    at trimSlashes (/project/node_modules/connect-api-mocker/api-mocker.js:29:15)
    at /project/node_modules/connect-api-mocker/api-mocker.js:85:15
    at call (/project/node_modules/connect/index.js:239:7)
    at next (/project/node_modules/connect/index.js:183:5)
    at next (/project/node_modules/connect/index.js:161:14)
    at SendStream.error (/project/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:159:13)
    at SendStream.error (/project/node_modules/serve-static/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/project/node_modules/serve-static/node_modules/send/index.js:421:12)
    at next (/project/node_modules/serve-static/node_modules/send/index.js:764:28)
    at /project/node_modules/serve-static/node_modules/send/index.js:772:23
    at FSReqWrap.oncomplete (fs.js:166:21)
```

Unless I'm doing something wrong, it seems that the problem is in missing baseUrl property. Which is an [Express specific thing](http://expressjs.com/en/api.html#req.baseUrl). And even with Express it's only set when router is used, so it's still might be undefined.

In my case with Connect request is an [IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage) object, which doesn't have such a property.

My setup:

```javascript
var connect = require('connect');
var app = connect();

var serveStatic = require('serve-static');
app.use(serveStatic(__dirname+'/public', {'index': ['index.html']}));
app.use('/mocks', serveStatic(__dirname+'/app/mocks'));

var apiMocker = require('connect-api-mocker');
app.use('/api', apiMocker('/mocks/api'));

app.listen(3333);
```

**Comment by muratcorlu** [comment]
You can set your `baseUrl` as the first parameter of `apiMocker` like:

```js
app.use(apiMocker('/api', 'mocks/api'));
```

If there is no second parameter, `apiMocker` tries to read baseUrl from the router. The only difference is, when you set `baseUrl` with `apiMocker` parameter, `apiMocker` will run for every request, will compare `baseUrl` with the requested path and decide if it should work or not. But if you set your `baseUrl` in express router, `apiMocker` will only run with url's that starts with that `baseUrl`.

But, you are right, that should work without Express or if it's not possible, it should warn. I'll think about that.

**Comment by silentvick** [comment]
It works now. Thanks, @muratcorlu !

**Comment by nnvhryb** [comment]
webpack dev server failed!

> TypeError: Cannot read property 'replace' of undefined  at trimSlashes
