### ISSUE TITLE
Custom response middleware without `body-parser`

### ISSUE THREAD

**Issue by raduserbanescu** [muratcorlu/connect-api-mocker#21]
As first discussed [here](https://github.com/muratcorlu/connect-api-mocker/issues/18#issuecomment-401046998), in version `1.3.5` there is a breaking change ([commit](https://github.com/muratcorlu/connect-api-mocker/commit/08d3b96d3d5af5c2f1d5169f35e3e91c99601894)) that affects custom response middleware.

[`body-parser`](https://github.com/expressjs/body-parser) was added before the custom middleware, which means that the request is consumed before it can reach the custom code. This means that the 'data' and 'end' request events are no longer called in the custom code. See this [issue](https://github.com/expressjs/body-parser/issues/296) for a better explanation.
Maybe revert to the old code (let the response unaltered) and add a config option to enable parsing the JSON body for you?

**Comment by muratcorlu** [comment]
Did you need to read raw request data in your custom responses? Or does lite-server tries to read raw request data? I didn't have a problem about that in my current custom responses. So maybe an example that shows the problem can help to find a better solution.

I'm also not very convinced about using body-parser but it also helps a lot in custom responses. Making it optional can be a good idea. For backward compatibility, maybe it can be enabled by default.

**Comment by raduserbanescu** [comment]
Below is my full custom middleware. It reads the request JSON and depending on the `messageID` it returns a different mock.

With the new `body-parser`, the request is already parsed and you can access the JSON from `req.body`. This of course makes things simpler for this example, but it breaks past implementations.

**POST.js**

```javascript
/* eslint-disable no-console */

'use strict';

const fs = require('fs');
const path = require('path');

// Process request and send response
function processRequest(req, reqBody, res) {
  let resBody;

  switch (reqBody.messageID) {
    case '416fnd0i6jdh5e4gny7fvlnji8grx75k':
    case 'w7got6jv2p1b5wkzryim100pe6hawpir':
      resBody = fs.readFileSync(path.join(__dirname, 'pdf.json'));
      break;
    case '1p879iprralgvbvfub0ac5l5nlpucohx':
      resBody = fs.readFileSync(path.join(__dirname, 'png.json'));
      break;
    case 'alx4ytywtb2ipkptr589ytridf1xxhvn':
      resBody = fs.readFileSync(path.join(__dirname, 'zip-pdf.json'));
      break;
    case 'olw8a1haupv44km0wvxrsso5mzj1svmt':
      resBody = fs.readFileSync(path.join(__dirname, 'zip-png.json'));
      break;
    default:
      resBody = fs.readFileSync(path.join(__dirname, 'not-available.json'));
  }

  res.setHeader('Content-Type', 'application/json');
  res.end(resBody);
}

// Middleware to handle incoming requests
module.exports = function (req, res) {
  let reqBody = [];

  req.on('data', (chunk) => {
    reqBody.push(chunk);
  });

  req.on('end', () => {
    reqBody = Buffer.concat(reqBody).toString();

    try {
      reqBody = JSON.parse(reqBody);

      processRequest(req, reqBody, res);
    } catch (e) {
      console.error(`request ${req.method} ${req.originalUrl} -> ${e.message}`);
    }
  });

  req.on('error', (e) => {
    console.error(`request ${req.method} ${req.originalUrl} -> ${e.message}`);
  });

  req.on('aborted', () => {
    console.log(`request ${req.method} ${req.originalUrl} -> Connection aborted`);
  });

  req.on('close', () => {
    console.log(`request ${req.method} ${req.originalUrl} -> Connection closed`);
  });
};
```

**Comment by muratcorlu** [comment]
Because of `body-parser` is already there, you don't need to read json body manually. You could just run `processRequest(req, req.body, res);`

**Comment by muratcorlu** [comment]
I got your point. Actually with body-parser your code will be way simpler than this but making a breaking change is not good, of course. Ok, let's try to add an option to disable built-in body-parser.

**Comment by valeriiudodov** [comment]
Is there a way to avoid body-parser nowadays?
By checking the code it looks like body-parser still got executed prior.

**Comment by muratcorlu** [comment]
Yes, you are right. I'll try to check if it's easy to do. And if so, I'll do the fix today.

**Comment by vudodov** [comment]
Thank you for taking care of it.
Since `body-parser` is a default tool used to parse body, I've added a [small PR](https://github.com/muratcorlu/connect-api-mocker/pull/38) to unlock its more detailed configuration

**Comment by muratcorlu** [comment]
Now, we can customise body-parser settings with the contribution of @vudodov. Thanks!

But for close this issue, we need to give a chance to disable body-parser completely.

**Comment by vudodov** [comment]
Done, but it will introduce breaking change. <bias> However it feels like it makes sense to have it like that. </bias> Let me know, what do you think
