### ISSUE TITLE
Parse FormData request

### ISSUE THREAD

**Issue by chr1s1k** [muratcorlu/connect-api-mocker#60]
Hi there,

is it possible to read and parse data from a request that are being sent as `FormData`?

```javascript
const formData = new FormData()
formData.append('param1', 'value1')
formData.append('param2', 'value2')

fetch('/api/mock-url', {
  method: 'POST',
  body: formData,
})
```

And then in `api/mock-url/POST.js`

```javascript
module.exports = function (request, response) {
  // ???
}
```

**Comment by muratcorlu** [comment]
connect-api-mocker uses body-parser for parsing request bodies. And it's possible to set the type of request body for body-parser as follows:

```js
apiMocker('/text', {
  target: 'test/mocks',
  bodyParser: {
    type: 'urlencoded',
    options: { extended: true }
  }
})
```

For other options of bodyParser.urlencoded you can check document: https://github.com/expressjs/body-parser#bodyparserurlencodedoptions

Hopefully that will help.
