### ISSUE TITLE
generate JSON files

### ISSUE THREAD

**Issue by jucasoft** [muratcorlu/connect-api-mocker#79]
hi everyone, I hope I understand correctly, this library does not generate JSON files? correct?

I was starting to develop a library that would allow me to generate JSON files, does something like this already exist?

I am so lucky to have this library in my life.
:)

**Comment by muratcorlu** [comment]
Hello. No, this is not for generating JSON files. This is for creating a REST api (for mocking a real/remote one) by creating JSON (or JS) files by yourself.

I have a companion project named [cli-api-mocker](https://github.com/muratcorlu/cli-api-mocker), which has a "[capture mode](https://github.com/muratcorlu/cli-api-mocker#capture-mode)" allows you to auto generate mock json files with real answers coming from real REST API. But I don't you meant something like that 😊
